import style from "@/components/layout/PageLayout.module.css";
import { NavBar } from "@/components/layout/NavBar";
import React from "react";
import Head from "next/head";
import { assemblePageTitle } from "@/components/layout/PageLayout.utils";

interface Props {
  title?: string;
  children: React.ReactNode;
}

export const PageLayout = ({ title, children }: Props) => {
  const titleAssembled = assemblePageTitle(title);
  return (
    <>
      <Head>
        <title>{titleAssembled}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={style.main}>{children}</main>
    </>
  );
};
