import style from "@/components/layout/page-layout/PageLayout.module.css";
import { NavBar } from "@/components/layout/navbar/NavBar";
import React from "react";
import Head from "next/head";
import { assemblePageTitle } from "@/components/layout/PageLayout.utils";
import { Breadcrumb } from "@/components/layout/header/Breadcrumb";
import { Header } from "@/components/layout/header/Header";

interface Props {
  title?: string;
  children: React.ReactNode;
  breadcrumbs?: Array<Breadcrumb>;
  headerComponent?: React.ReactNode;
}

export const PageLayout = ({
  title,
  breadcrumbs,
  headerComponent,
  children,
}: Props) => {
  const titleAssembled = assemblePageTitle(title);
  return (
    <>
      <Head>
        <title>{titleAssembled}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={style.main}>
        <Header
          title={title}
          breadcrumbs={breadcrumbs}
          component={headerComponent}
        />
        {children}
      </main>
    </>
  );
};
